update_fastlane
fastlane_version "1.109.0"
generated_fastfile_id "d97ea7fd-6d42-45e3-951b-51b933bb8116"

default_platform :ios

lane :beta do
  gym(
    scheme: “release-victorious”,
    workspace: “/Users/michaelmontgomery/Desktop/Ruby /fastlane/victorious.xcworkspace”,
    export_method: "app-store”,
    clean: “true”,
    output_directory:”/Users/michaelmontgomery/Desktop/Ruby /fastlane/ipaFiles”,
  )

  # upload to Testflight
  pilot(skip_waiting_for_build_processing: true)

  # slack(
  #   slack_url: "https://hooks.slack.com/services/IDS"
  # )
end
