[{u'color': u'disabled',
  u'name': u'iOS Demo Build',
  u'url': u'http://devs-imac.local:8080/job/iOS%20Demo%20Build/'},
 {u'color': u'blue',
  u'name': u'iOS QA Build',
  u'url': u'http://devs-imac.local:8080/job/iOS%20QA%20Build/'},
 {u'color': u'red',
  u'name': u'iOS Stable Build',
  u'url': u'http://devs-imac.local:8080/job/iOS%20Stable%20Build/'},
 {u'color': u'blue',
  u'name': u'iOS Staging Build',
  u'url': u'http://devs-imac.local:8080/job/iOS%20Staging%20Build/'},
 {u'color': u'blue',
  u'name': u'iOS UI Automation and Unit Testing',
  u'url': u'http://devs-imac.local:8080/job/iOS%20UI%20Automation%20and%20Unit%20Testing/'}]