[{u'task': {u'url': u'http://devs-imac.local:8080/job/iOS%20UI%20Automation%20and%20Unit%20Testing/', u'color': u'blue',
            u'name': u'iOS UI Automation and Unit Testing'}, u'stuck': False, u'url': u'queue/item/1131/',
  u'inQueueSince': 1439000762711, u'actions': [{u'parameters': [{u'name': u'APP_NAMES', u'value': u'victorious'},
                                                                {u'name': u'SEND_NOTIFICATIONS', u'value': True},
                                                                {u'name': u'sha1',
                                                                 u'value': u'a49a853fdd87863a34e33c3d51437cc72361f229'},
                                                                {u'name': u'ghprbActualCommit',
                                                                 u'value': u'a49a853fdd87863a34e33c3d51437cc72361f229'},
                                                                {u'name': u'ghprbActualCommitAuthor',
                                                                 u'value': u'feef'},
                                                                {u'name': u'ghprbActualCommitAuthorEmail',
                                                                 u'value': u'fifihypnophonic@gmail.com'},
                                                                {u'name': u'ghprbTriggerAuthor', u'value': u''},
                                                                {u'name': u'ghprbTriggerAuthorEmail', u'value': u''},
                                                                {u'name': u'ghprbPullId', u'value': u'1627'},
                                                                {u'name': u'ghprbTargetBranch', u'value': u'dev'},
                                                                {u'name': u'ghprbSourceBranch', u'value': u'IOS-3197'},
                                                                {u'name': u'GIT_BRANCH', u'value': u'IOS-3197'},
                                                                {u'name': u'ghprbPullAuthorEmail', u'value': u''},
                                                                {u'name': u'ghprbPullDescription',
                                                                 u'value': u'GitHub pull request #1627 of commit a49a853fdd87863a34e33c3d51437cc72361f229.'},
                                                                {u'name': u'ghprbPullTitle',
                                                                 u'value': u'Ios 3197 - Marquee refactor to work as a shelf'},
                                                                {u'name': u'ghprbPullLink',
                                                                 u'value': u'https://github.com/Victorious/VictoriousiOS/pull/1627'}]},
                                               {u'scmName': u'', u'buildsByBranchName': {
                                                   u'refs/remotes/origin/dev': {u'buildNumber': 2, u'buildResult': None,
                                                                                u'marked': {
                                                                                    u'SHA1': u'ae1bdc3ae7066c14eb3ad51cb8e1daa0d811500b',
                                                                                    u'branch': [{
                                                                                                    u'SHA1': u'ae1bdc3ae7066c14eb3ad51cb8e1daa0d811500b',
                                                                                                    u'name': u'refs/remotes/origin/dev'}]},
                                                                                u'revision': {
                                                                                    u'SHA1': u'ae1bdc3ae7066c14eb3ad51cb8e1daa0d811500b',
                                                                                    u'branch': [{
                                                                                                    u'SHA1': u'ae1bdc3ae7066c14eb3ad51cb8e1daa0d811500b',
                                                                                                    u'name': u'refs/remotes/origin/dev'}]}},
                                                   u'origin/IOS-1780_receiptValidation': {u'buildNumber': 14,
                                                                                          u'buildResult': None,
                                                                                          u'marked': {
                                                                                              u'SHA1': u'2506a87754c8d8b46f7f8a9815c5041979b4faa6',
                                                                                              u'branch': [{
                                                                                                              u'SHA1': u'2506a87754c8d8b46f7f8a9815c5041979b4faa6',
                                                                                                              u'name': u'origin/IOS-1780_receiptValidation'}]},
                                                                                          u'revision': {
                                                                                              u'SHA1': u'2506a87754c8d8b46f7f8a9815c5041979b4faa6',
                                                                                              u'branch': [{
                                                                                                              u'SHA1': u'2506a87754c8d8b46f7f8a9815c5041979b4faa6',
                                                                                                              u'name': u'origin/IOS-1780_receiptValidation'}]}},
                                                   u'origin/IOS-2395': {u'buildNumber': 17, u'buildResult': None,
                                                                        u'marked': {
                                                                            u'SHA1': u'77427090db1b805b2cb3143ab3fbcd5077855949',
                                                                            u'branch': [{
                                                                                            u'SHA1': u'77427090db1b805b2cb3143ab3fbcd5077855949',
                                                                                            u'name': u'origin/IOS-2395'}]},
                                                                        u'revision': {
                                                                            u'SHA1': u'77427090db1b805b2cb3143ab3fbcd5077855949',
                                                                            u'branch': [{
                                                                                            u'SHA1': u'77427090db1b805b2cb3143ab3fbcd5077855949',
                                                                                            u'name': u'origin/IOS-2395'}]}},
                                                   u'detached': {u'buildNumber': 23, u'buildResult': None, u'marked': {
                                                       u'SHA1': u'5d67f502bd2a6a27cfe1fd8087d8df3f90f7ede0',
                                                       u'branch': [
                                                           {u'SHA1': u'5d67f502bd2a6a27cfe1fd8087d8df3f90f7ede0',
                                                            u'name': u'detached'}]}, u'revision': {
                                                       u'SHA1': u'5d67f502bd2a6a27cfe1fd8087d8df3f90f7ede0',
                                                       u'branch': [
                                                           {u'SHA1': u'5d67f502bd2a6a27cfe1fd8087d8df3f90f7ede0',
                                                            u'name': u'detached'}]}},
                                                   u'origin/IOS-2601': {u'buildNumber': 15, u'buildResult': None,
                                                                        u'marked': {
                                                                            u'SHA1': u'391f538cf3b3e0d5f651dbd6176128d1d2a587a5',
                                                                            u'branch': [{
                                                                                            u'SHA1': u'391f538cf3b3e0d5f651dbd6176128d1d2a587a5',
                                                                                            u'name': u'origin/IOS-2601'}]},
                                                                        u'revision': {
                                                                            u'SHA1': u'391f538cf3b3e0d5f651dbd6176128d1d2a587a5',
                                                                            u'branch': [{
                                                                                            u'SHA1': u'391f538cf3b3e0d5f651dbd6176128d1d2a587a5',
                                                                                            u'name': u'origin/IOS-2601'}]}},
                                                   u'origin/IOS-2539': {u'buildNumber': 16, u'buildResult': None,
                                                                        u'marked': {
                                                                            u'SHA1': u'857397c8620c01b0c090cacf39a75364373a42e8',
                                                                            u'branch': [{
                                                                                            u'SHA1': u'857397c8620c01b0c090cacf39a75364373a42e8',
                                                                                            u'name': u'origin/IOS-2539'}]},
                                                                        u'revision': {
                                                                            u'SHA1': u'857397c8620c01b0c090cacf39a75364373a42e8',
                                                                            u'branch': [{
                                                                                            u'SHA1': u'857397c8620c01b0c090cacf39a75364373a42e8',
                                                                                            u'name': u'origin/IOS-2539'}]}}},
                                                u'remoteUrls': [u'https://github.com/Victorious/VictoriousiOS.git'],
                                                u'lastBuiltRevision': {
                                                    u'SHA1': u'5d67f502bd2a6a27cfe1fd8087d8df3f90f7ede0', u'branch': [
                                                        {u'SHA1': u'5d67f502bd2a6a27cfe1fd8087d8df3f90f7ede0',
                                                         u'name': u'detached'}]}}, {u'causes': [
            {u'shortDescription': u'GitHub pull request #1627 of commit a49a853fdd87863a34e33c3d51437cc72361f229.'}]}],
  u'why': None, u'buildable': False,
  u'params': u'\nAPP_NAMES=victorious\nSEND_NOTIFICATIONS=true\nsha1=a49a853fdd87863a34e33c3d51437cc72361f229\nghprbActualCommit=a49a853fdd87863a34e33c3d51437cc72361f229\nghprbActualCommitAuthor=feef\nghprbActualCommitAuthorEmail=fifihypnophonic@gmail.com\nghprbTriggerAuthor=\nghprbTriggerAuthorEmail=\nghprbPullId=1627\nghprbTargetBranch=dev\nghprbSourceBranch=IOS-3197\nGIT_BRANCH=IOS-3197\nghprbPullAuthorEmail=\nghprbPullDescription=GitHub pull request #1627 of commit a49a853fdd87863a34e33c3d51437cc72361f229.\nghprbPullTitle=Ios 3197 - Marquee refactor to work as a shelf\nghprbPullLink=https://github.com/Victorious/VictoriousiOS/pull/1627',
  u'buildableStartMilliseconds': 1439000769547, u'id': 1131, u'blocked': True}, {
     u'task': {u'url': u'http://devs-imac.local:8080/job/iOS%20Stable%20Build/', u'color': u'red',
               u'name': u'iOS Stable Build'}, u'stuck': False, u'url': u'queue/item/1139/',
     u'inQueueSince': 1439073875128, u'actions': [{u'parameters': [{u'name': u'APP_NAMES', u'value': u'jesslizama'},
                                                                   {u'name': u'SEND_NOTIFICATIONS', u'value': True}]}, {
                                                      u'causes': [{u'userName': u'VAMS', u'userId': u'vams',
                                                                   u'shortDescription': u'Started by user VAMS'},
                                                                  {u'userName': u'VAMS', u'userId': u'vams',
                                                                   u'shortDescription': u'Started by user VAMS'},
                                                                  {u'userName': u'VAMS', u'userId': u'vams',
                                                                   u'shortDescription': u'Started by user VAMS'},
                                                                  {u'userName': u'VAMS', u'userId': u'vams',
                                                                   u'shortDescription': u'Started by user VAMS'}]}],
     u'why': u'Build #607 is already in progress (ETA:N/A)', u'buildable': False,
     u'params': u'\nAPP_NAMES=jesslizama\nSEND_NOTIFICATIONS=true', u'buildableStartMilliseconds': 1439073880493,
     u'id': 1139, u'blocked': True}, {
     u'task': {u'url': u'http://devs-imac.local:8080/job/iOS%20Stable%20Build/', u'color': u'red',
               u'name': u'iOS Stable Build'}, u'stuck': False, u'url': u'queue/item/1140/',
     u'inQueueSince': 1439073875749, u'actions': [{u'parameters': [{u'name': u'APP_NAMES', u'value': u'JessicaLizama'},
                                                                   {u'name': u'SEND_NOTIFICATIONS', u'value': True}]}, {
                                                      u'causes': [{u'userName': u'VAMS', u'userId': u'vams',
                                                                   u'shortDescription': u'Started by user VAMS'},
                                                                  {u'userName': u'VAMS', u'userId': u'vams',
                                                                   u'shortDescription': u'Started by user VAMS'}]}],
     u'why': u'Build #607 is already in progress (ETA:N/A)', u'buildable': False,
     u'params': u'\nAPP_NAMES=JessicaLizama\nSEND_NOTIFICATIONS=true', u'buildableStartMilliseconds': 1439073885563,
     u'id': 1140, u'blocked': True}, {
     u'task': {u'url': u'http://devs-imac.local:8080/job/iOS%20Stable%20Build/', u'color': u'red',
               u'name': u'iOS Stable Build'}, u'stuck': False, u'url': u'queue/item/1141/',
     u'inQueueSince': 1439074420084, u'actions': [{u'parameters': [{u'name': u'APP_NAMES', u'value': u'gtchannel'},
                                                                   {u'name': u'SEND_NOTIFICATIONS', u'value': True}]}, {
                                                      u'causes': [{u'userName': u'VAMS', u'userId': u'vams',
                                                                   u'shortDescription': u'Started by user VAMS'}]}],
     u'why': u'Build #607 is already in progress (ETA:N/A)', u'buildable': False,
     u'params': u'\nAPP_NAMES=gtchannel\nSEND_NOTIFICATIONS=true', u'buildableStartMilliseconds': 1439074427067,
     u'id': 1141, u'blocked': True}, {
     u'task': {u'url': u'http://devs-imac.local:8080/job/iOS%20Stable%20Build/', u'color': u'red',
               u'name': u'iOS Stable Build'}, u'stuck': False, u'url': u'queue/item/1142/',
     u'inQueueSince': 1439074965128, u'actions': [{u'parameters': [{u'name': u'APP_NAMES', u'value': u'eatyourkimchi'},
                                                                   {u'name': u'SEND_NOTIFICATIONS', u'value': True}]}, {
                                                      u'causes': [{u'userName': u'VAMS', u'userId': u'vams',
                                                                   u'shortDescription': u'Started by user VAMS'}]}],
     u'why': u'Build #607 is already in progress (ETA:N/A)', u'buildable': False,
     u'params': u'\nAPP_NAMES=eatyourkimchi\nSEND_NOTIFICATIONS=true', u'buildableStartMilliseconds': 1439074971467,
     u'id': 1142, u'blocked': True}, {
     u'task': {u'url': u'http://devs-imac.local:8080/job/iOS%20Stable%20Build/', u'color': u'red',
               u'name': u'iOS Stable Build'}, u'stuck': False, u'url': u'queue/item/1143/',
     u'inQueueSince': 1439075500126, u'actions': [{u'parameters': [
        {u'name': u'APP_NAMES', u'value': u'fitnessblenderworkouts'},
        {u'name': u'SEND_NOTIFICATIONS', u'value': True}]}, {u'causes': [
        {u'userName': u'VAMS', u'userId': u'vams', u'shortDescription': u'Started by user VAMS'}]}],
     u'why': u'Build #607 is already in progress (ETA:N/A)', u'buildable': False,
     u'params': u'\nAPP_NAMES=fitnessblenderworkouts\nSEND_NOTIFICATIONS=true',
     u'buildableStartMilliseconds': 1439075505680, u'id': 1143, u'blocked': True}, {
     u'task': {u'url': u'http://devs-imac.local:8080/job/iOS%20Stable%20Build/', u'color': u'red',
               u'name': u'iOS Stable Build'}, u'stuck': False, u'url': u'queue/item/1144/',
     u'inQueueSince': 1439076000142, u'actions': [{u'parameters': [{u'name': u'APP_NAMES', u'value': u'ryanhiga'},
                                                                   {u'name': u'SEND_NOTIFICATIONS', u'value': True}]}, {
                                                      u'causes': [{u'userName': u'VAMS', u'userId': u'vams',
                                                                   u'shortDescription': u'Started by user VAMS'}]}],
     u'why': u'Build #607 is already in progress (ETA:N/A)', u'buildable': False,
     u'params': u'\nAPP_NAMES=ryanhiga\nSEND_NOTIFICATIONS=true', u'buildableStartMilliseconds': 1439076009201,
     u'id': 1144, u'blocked': True}, {
     u'task': {u'url': u'http://devs-imac.local:8080/job/iOS%20Stable%20Build/', u'color': u'red',
               u'name': u'iOS Stable Build'}, u'stuck': False, u'url': u'queue/item/1145/',
     u'inQueueSince': 1439076160109, u'actions': [{u'parameters': [{u'name': u'APP_NAMES', u'value': u'nitrocircus'},
                                                                   {u'name': u'SEND_NOTIFICATIONS', u'value': True}]}, {
                                                      u'causes': [{u'userName': u'VAMS', u'userId': u'vams',
                                                                   u'shortDescription': u'Started by user VAMS'}]}],
     u'why': u'Build #607 is already in progress (ETA:N/A)', u'buildable': False,
     u'params': u'\nAPP_NAMES=nitrocircus\nSEND_NOTIFICATIONS=true', u'buildableStartMilliseconds': 1439076168121,
     u'id': 1145, u'blocked': True}, {
     u'task': {u'url': u'http://devs-imac.local:8080/job/iOS%20Stable%20Build/', u'color': u'red',
               u'name': u'iOS Stable Build'}, u'stuck': False, u'url': u'queue/item/1146/',
     u'inQueueSince': 1439076480162, u'actions': [{u'parameters': [{u'name': u'APP_NAMES', u'value': u'unicornisland'},
                                                                   {u'name': u'SEND_NOTIFICATIONS', u'value': True}]}, {
                                                      u'causes': [{u'userName': u'VAMS', u'userId': u'vams',
                                                                   u'shortDescription': u'Started by user VAMS'}]}],
     u'why': u'Build #607 is already in progress (ETA:N/A)', u'buildable': False,
     u'params': u'\nAPP_NAMES=unicornisland\nSEND_NOTIFICATIONS=true', u'buildableStartMilliseconds': 1439076486416,
     u'id': 1146, u'blocked': True}, {
     u'task': {u'url': u'http://devs-imac.local:8080/job/iOS%20Stable%20Build/', u'color': u'red',
               u'name': u'iOS Stable Build'}, u'stuck': False, u'url': u'queue/item/1147/',
     u'inQueueSince': 1439076715123, u'actions': [{u'parameters': [
        {u'name': u'APP_NAMES', u'value': u'eleventhgorgeous'}, {u'name': u'SEND_NOTIFICATIONS', u'value': True}]}, {
                                                      u'causes': [{u'userName': u'VAMS', u'userId': u'vams',
                                                                   u'shortDescription': u'Started by user VAMS'}]}],
     u'why': u'Build #607 is already in progress (ETA:N/A)', u'buildable': False,
     u'params': u'\nAPP_NAMES=eleventhgorgeous\nSEND_NOTIFICATIONS=true', u'buildableStartMilliseconds': 1439076722731,
     u'id': 1147, u'blocked': True}, {
     u'task': {u'url': u'http://devs-imac.local:8080/job/iOS%20Stable%20Build/', u'color': u'red',
               u'name': u'iOS Stable Build'}, u'stuck': False, u'url': u'queue/item/1148/',
     u'inQueueSince': 1439077035172, u'actions': [{u'parameters': [{u'name': u'APP_NAMES', u'value': u'alltime10s'},
                                                                   {u'name': u'SEND_NOTIFICATIONS', u'value': True}]}, {
                                                      u'causes': [{u'userName': u'VAMS', u'userId': u'vams',
                                                                   u'shortDescription': u'Started by user VAMS'}]}],
     u'why': u'Build #607 is already in progress (ETA:N/A)', u'buildable': False,
     u'params': u'\nAPP_NAMES=alltime10s\nSEND_NOTIFICATIONS=true', u'buildableStartMilliseconds': 1439077040777,
     u'id': 1148, u'blocked': True}, {
     u'task': {u'url': u'http://devs-imac.local:8080/job/iOS%20Stable%20Build/', u'color': u'red',
               u'name': u'iOS Stable Build'}, u'stuck': False, u'url': u'queue/item/1149/',
     u'inQueueSince': 1439077325142, u'actions': [{u'parameters': [{u'name': u'APP_NAMES', u'value': u'imjennim'},
                                                                   {u'name': u'SEND_NOTIFICATIONS', u'value': True}]}, {
                                                      u'causes': [{u'userName': u'VAMS', u'userId': u'vams',
                                                                   u'shortDescription': u'Started by user VAMS'}]}],
     u'why': u'Build #607 is already in progress (ETA:N/A)', u'buildable': False,
     u'params': u'\nAPP_NAMES=imjennim\nSEND_NOTIFICATIONS=true', u'buildableStartMilliseconds': 1439077333521,
     u'id': 1149, u'blocked': True}, {
     u'task': {u'url': u'http://devs-imac.local:8080/job/iOS%20Stable%20Build/', u'color': u'red',
               u'name': u'iOS Stable Build'}, u'stuck': False, u'url': u'queue/item/1150/',
     u'inQueueSince': 1439077470193, u'actions': [{u'parameters': [{u'name': u'APP_NAMES', u'value': u'beingindian'},
                                                                   {u'name': u'SEND_NOTIFICATIONS', u'value': True}]}, {
                                                      u'causes': [{u'userName': u'VAMS', u'userId': u'vams',
                                                                   u'shortDescription': u'Started by user VAMS'}]}],
     u'why': u'Build #607 is already in progress (ETA:N/A)', u'buildable': False,
     u'params': u'\nAPP_NAMES=beingindian\nSEND_NOTIFICATIONS=true', u'buildableStartMilliseconds': 1439077477319,
     u'id': 1150, u'blocked': True}, {
     u'task': {u'url': u'http://devs-imac.local:8080/job/iOS%20Stable%20Build/', u'color': u'red',
               u'name': u'iOS Stable Build'}, u'stuck': False, u'url': u'queue/item/1151/',
     u'inQueueSince': 1439077645153, u'actions': [{u'parameters': [{u'name': u'APP_NAMES', u'value': u'strawburry17'},
                                                                   {u'name': u'SEND_NOTIFICATIONS', u'value': True}]}, {
                                                      u'causes': [{u'userName': u'VAMS', u'userId': u'vams',
                                                                   u'shortDescription': u'Started by user VAMS'}]}],
     u'why': u'Build #607 is already in progress (ETA:N/A)', u'buildable': False,
     u'params': u'\nAPP_NAMES=strawburry17\nSEND_NOTIFICATIONS=true', u'buildableStartMilliseconds': 1439077651890,
     u'id': 1151, u'blocked': True}, {
     u'task': {u'url': u'http://devs-imac.local:8080/job/iOS%20Stable%20Build/', u'color': u'red',
               u'name': u'iOS Stable Build'}, u'stuck': False, u'url': u'queue/item/1152/',
     u'inQueueSince': 1439079880265, u'actions': [{u'parameters': [{u'name': u'APP_NAMES', u'value': u'thepalmcakes'},
                                                                   {u'name': u'SEND_NOTIFICATIONS', u'value': True}]}, {
                                                      u'causes': [{u'userName': u'VAMS', u'userId': u'vams',
                                                                   u'shortDescription': u'Started by user VAMS'}]}],
     u'why': u'Build #607 is already in progress (ETA:N/A)', u'buildable': False,
     u'params': u'\nAPP_NAMES=thepalmcakes\nSEND_NOTIFICATIONS=true', u'buildableStartMilliseconds': 1439079885869,
     u'id': 1152, u'blocked': True}, {
     u'task': {u'url': u'http://devs-imac.local:8080/job/iOS%20Stable%20Build/', u'color': u'red',
               u'name': u'iOS Stable Build'}, u'stuck': False, u'url': u'queue/item/1153/',
     u'inQueueSince': 1439100991002, u'actions': [{u'parameters': [{u'name': u'APP_NAMES', u'value': u'peterhollens'},
                                                                   {u'name': u'SEND_NOTIFICATIONS', u'value': True}]}, {
                                                      u'causes': [{u'userName': u'VAMS', u'userId': u'vams',
                                                                   u'shortDescription': u'Started by user VAMS'},
                                                                  {u'userName': u'VAMS', u'userId': u'vams',
                                                                   u'shortDescription': u'Started by user VAMS'},
                                                                  {u'userName': u'VAMS', u'userId': u'vams',
                                                                   u'shortDescription': u'Started by user VAMS'},
                                                                  {u'userName': u'VAMS', u'userId': u'vams',
                                                                   u'shortDescription': u'Started by user VAMS'}]}],
     u'why': u'Build #607 is already in progress (ETA:N/A)', u'buildable': False,
     u'params': u'\nAPP_NAMES=peterhollens\nSEND_NOTIFICATIONS=true', u'buildableStartMilliseconds': 1439100999955,
     u'id': 1153, u'blocked': True}, {
     u'task': {u'url': u'http://devs-imac.local:8080/job/iOS%20Stable%20Build/', u'color': u'red',
               u'name': u'iOS Stable Build'}, u'stuck': False, u'url': u'queue/item/1154/',
     u'inQueueSince': 1439101145843, u'actions': [{u'parameters': [{u'name': u'APP_NAMES', u'value': u'PeterHollens'},
                                                                   {u'name': u'SEND_NOTIFICATIONS', u'value': True}]}, {
                                                      u'causes': [{u'userName': u'VAMS', u'userId': u'vams',
                                                                   u'shortDescription': u'Started by user VAMS'}]}],
     u'why': u'Build #607 is already in progress (ETA:N/A)', u'buildable': False,
     u'params': u'\nAPP_NAMES=PeterHollens\nSEND_NOTIFICATIONS=true', u'buildableStartMilliseconds': 1439101153857,
     u'id': 1154, u'blocked': True}, {
     u'task': {u'url': u'http://devs-imac.local:8080/job/iOS%20Stable%20Build/', u'color': u'red',
               u'name': u'iOS Stable Build'}, u'stuck': False, u'url': u'queue/item/1155/',
     u'inQueueSince': 1439107383926, u'actions': [{u'parameters': [{u'name': u'APP_NAMES', u'value': u'whistlesports'},
                                                                   {u'name': u'SEND_NOTIFICATIONS', u'value': True}]}, {
                                                      u'causes': [{u'userName': u'VAMS', u'userId': u'vams',
                                                                   u'shortDescription': u'Started by user VAMS'},
                                                                  {u'userName': u'VAMS', u'userId': u'vams',
                                                                   u'shortDescription': u'Started by user VAMS'},
                                                                  {u'userName': u'VAMS', u'userId': u'vams',
                                                                   u'shortDescription': u'Started by user VAMS'},
                                                                  {u'userName': u'VAMS', u'userId': u'vams',
                                                                   u'shortDescription': u'Started by user VAMS'},
                                                                  {u'userName': u'VAMS', u'userId': u'vams',
                                                                   u'shortDescription': u'Started by user VAMS'}]}],
     u'why': u'Build #607 is already in progress (ETA:N/A)', u'buildable': False,
     u'params': u'\nAPP_NAMES=whistlesports\nSEND_NOTIFICATIONS=true', u'buildableStartMilliseconds': 1439107389951,
     u'id': 1155, u'blocked': True}, {
     u'task': {u'url': u'http://devs-imac.local:8080/job/iOS%20Stable%20Build/', u'color': u'red',
               u'name': u'iOS Stable Build'}, u'stuck': False, u'url': u'queue/item/1156/',
     u'inQueueSince': 1439107391101, u'actions': [{u'parameters': [{u'name': u'APP_NAMES', u'value': u'WhistleSports'},
                                                                   {u'name': u'SEND_NOTIFICATIONS', u'value': True}]}, {
                                                      u'causes': [{u'userName': u'VAMS', u'userId': u'vams',
                                                                   u'shortDescription': u'Started by user VAMS'}]}],
     u'why': u'Build #607 is already in progress (ETA:N/A)', u'buildable': False,
     u'params': u'\nAPP_NAMES=WhistleSports\nSEND_NOTIFICATIONS=true', u'buildableStartMilliseconds': 1439107400244,
     u'id': 1156, u'blocked': True}, {
     u'task': {u'url': u'http://devs-imac.local:8080/job/iOS%20Stable%20Build/', u'color': u'red',
               u'name': u'iOS Stable Build'}, u'stuck': False, u'url': u'queue/item/1157/',
     u'inQueueSince': 1439111366266, u'actions': [{u'parameters': [{u'name': u'APP_NAMES', u'value': u'andreaschoice'},
                                                                   {u'name': u'SEND_NOTIFICATIONS', u'value': True}]}, {
                                                      u'causes': [{u'userName': u'VAMS', u'userId': u'vams',
                                                                   u'shortDescription': u'Started by user VAMS'},
                                                                  {u'userName': u'VAMS', u'userId': u'vams',
                                                                   u'shortDescription': u'Started by user VAMS'},
                                                                  {u'userName': u'VAMS', u'userId': u'vams',
                                                                   u'shortDescription': u'Started by user VAMS'},
                                                                  {u'userName': u'VAMS', u'userId': u'vams',
                                                                   u'shortDescription': u'Started by user VAMS'}]}],
     u'why': u'Build #607 is already in progress (ETA:N/A)', u'buildable': False,
     u'params': u'\nAPP_NAMES=andreaschoice\nSEND_NOTIFICATIONS=true', u'buildableStartMilliseconds': 1439111372861,
     u'id': 1157, u'blocked': True}, {
     u'task': {u'url': u'http://devs-imac.local:8080/job/iOS%20Stable%20Build/', u'color': u'red',
               u'name': u'iOS Stable Build'}, u'stuck': False, u'url': u'queue/item/1158/',
     u'inQueueSince': 1439111381236, u'actions': [{u'parameters': [{u'name': u'APP_NAMES', u'value': u'AndreasChoice'},
                                                                   {u'name': u'SEND_NOTIFICATIONS', u'value': True}]}, {
                                                      u'causes': [{u'userName': u'VAMS', u'userId': u'vams',
                                                                   u'shortDescription': u'Started by user VAMS'}]}],
     u'why': u'Build #607 is already in progress (ETA:N/A)', u'buildable': False,
     u'params': u'\nAPP_NAMES=AndreasChoice\nSEND_NOTIFICATIONS=true', u'buildableStartMilliseconds': 1439111388300,
     u'id': 1158, u'blocked': True}, {
     u'task': {u'url': u'http://devs-imac.local:8080/job/iOS%20Stable%20Build/', u'color': u'red',
               u'name': u'iOS Stable Build'}, u'stuck': False, u'url': u'queue/item/1159/',
     u'inQueueSince': 1439116896637, u'actions': [{u'parameters': [{u'name': u'APP_NAMES', u'value': u'wongfu'},
                                                                   {u'name': u'SEND_NOTIFICATIONS', u'value': True}]}, {
                                                      u'causes': [{u'userName': u'VAMS', u'userId': u'vams',
                                                                   u'shortDescription': u'Started by user VAMS'},
                                                                  {u'userName': u'VAMS', u'userId': u'vams',
                                                                   u'shortDescription': u'Started by user VAMS'}]}],
     u'why': u'Build #607 is already in progress (ETA:N/A)', u'buildable': False,
     u'params': u'\nAPP_NAMES=wongfu\nSEND_NOTIFICATIONS=true', u'buildableStartMilliseconds': 1439116902139,
     u'id': 1159, u'blocked': True}, {
     u'task': {u'url': u'http://devs-imac.local:8080/job/iOS%20Stable%20Build/', u'color': u'red',
               u'name': u'iOS Stable Build'}, u'stuck': False, u'url': u'queue/item/1160/',
     u'inQueueSince': 1439116986396, u'actions': [{u'parameters': [{u'name': u'APP_NAMES', u'value': u'WongFu'},
                                                                   {u'name': u'SEND_NOTIFICATIONS', u'value': True}]}, {
                                                      u'causes': [{u'userName': u'VAMS', u'userId': u'vams',
                                                                   u'shortDescription': u'Started by user VAMS'}]}],
     u'why': u'Build #607 is already in progress (ETA:N/A)', u'buildable': False,
     u'params': u'\nAPP_NAMES=WongFu\nSEND_NOTIFICATIONS=true', u'buildableStartMilliseconds': 1439116994560,
     u'id': 1160, u'blocked': True}, {
     u'task': {u'url': u'http://devs-imac.local:8080/job/iOS%20UI%20Automation%20and%20Unit%20Testing/',
               u'color': u'blue', u'name': u'iOS UI Automation and Unit Testing'}, u'stuck': True,
     u'url': u'queue/item/1130/', u'inQueueSince': 1438992661730, u'actions': [{u'parameters': [
        {u'name': u'APP_NAMES', u'value': u'victorious'}, {u'name': u'SEND_NOTIFICATIONS', u'value': True},
        {u'name': u'sha1', u'value': u'origin/pr/1628/merge'},
        {u'name': u'ghprbActualCommit', u'value': u'e89f0d1b08877a775064c3169fe6475c2dbbaac4'},
        {u'name': u'ghprbActualCommitAuthor', u'value': u'Steven F Petteruti'},
        {u'name': u'ghprbActualCommitAuthorEmail', u'value': u'steven@stevens-mac-mini.local'},
        {u'name': u'ghprbTriggerAuthor', u'value': u''}, {u'name': u'ghprbTriggerAuthorEmail', u'value': u''},
        {u'name': u'ghprbPullId', u'value': u'1628'}, {u'name': u'ghprbTargetBranch', u'value': u'dev'},
        {u'name': u'ghprbSourceBranch', u'value': u'comment-animation'},
        {u'name': u'GIT_BRANCH', u'value': u'comment-animation'}, {u'name': u'ghprbPullAuthorEmail', u'value': u''},
        {u'name': u'ghprbPullDescription',
         u'value': u'GitHub pull request #1628 of commit e89f0d1b08877a775064c3169fe6475c2dbbaac4 automatically merged.'},
        {u'name': u'ghprbPullTitle', u'value': u'added a nice animation when user leaves a comment'},
        {u'name': u'ghprbPullLink', u'value': u'https://github.com/Victorious/VictoriousiOS/pull/1628'}]},
                                                                               {u'scmName': u'',
                                                                                u'buildsByBranchName': {
                                                                                    u'refs/remotes/origin/dev': {
                                                                                        u'buildNumber': 2,
                                                                                        u'buildResult': None,
                                                                                        u'marked': {
                                                                                            u'SHA1': u'ae1bdc3ae7066c14eb3ad51cb8e1daa0d811500b',
                                                                                            u'branch': [{
                                                                                                            u'SHA1': u'ae1bdc3ae7066c14eb3ad51cb8e1daa0d811500b',
                                                                                                            u'name': u'refs/remotes/origin/dev'}]},
                                                                                        u'revision': {
                                                                                            u'SHA1': u'ae1bdc3ae7066c14eb3ad51cb8e1daa0d811500b',
                                                                                            u'branch': [{
                                                                                                            u'SHA1': u'ae1bdc3ae7066c14eb3ad51cb8e1daa0d811500b',
                                                                                                            u'name': u'refs/remotes/origin/dev'}]}},
                                                                                    u'origin/IOS-1780_receiptValidation': {
                                                                                        u'buildNumber': 14,
                                                                                        u'buildResult': None,
                                                                                        u'marked': {
                                                                                            u'SHA1': u'2506a87754c8d8b46f7f8a9815c5041979b4faa6',
                                                                                            u'branch': [{
                                                                                                            u'SHA1': u'2506a87754c8d8b46f7f8a9815c5041979b4faa6',
                                                                                                            u'name': u'origin/IOS-1780_receiptValidation'}]},
                                                                                        u'revision': {
                                                                                            u'SHA1': u'2506a87754c8d8b46f7f8a9815c5041979b4faa6',
                                                                                            u'branch': [{
                                                                                                            u'SHA1': u'2506a87754c8d8b46f7f8a9815c5041979b4faa6',
                                                                                                            u'name': u'origin/IOS-1780_receiptValidation'}]}},
                                                                                    u'origin/IOS-2395': {
                                                                                        u'buildNumber': 17,
                                                                                        u'buildResult': None,
                                                                                        u'marked': {
                                                                                            u'SHA1': u'77427090db1b805b2cb3143ab3fbcd5077855949',
                                                                                            u'branch': [{
                                                                                                            u'SHA1': u'77427090db1b805b2cb3143ab3fbcd5077855949',
                                                                                                            u'name': u'origin/IOS-2395'}]},
                                                                                        u'revision': {
                                                                                            u'SHA1': u'77427090db1b805b2cb3143ab3fbcd5077855949',
                                                                                            u'branch': [{
                                                                                                            u'SHA1': u'77427090db1b805b2cb3143ab3fbcd5077855949',
                                                                                                            u'name': u'origin/IOS-2395'}]}},
                                                                                    u'detached': {u'buildNumber': 24,
                                                                                                  u'buildResult': None,
                                                                                                  u'marked': {
                                                                                                      u'SHA1': u'b868e71f5419311c3f921cf4ba443fb6d806baf1',
                                                                                                      u'branch': [{
                                                                                                                      u'SHA1': u'b868e71f5419311c3f921cf4ba443fb6d806baf1',
                                                                                                                      u'name': u'detached'}]},
                                                                                                  u'revision': {
                                                                                                      u'SHA1': u'b868e71f5419311c3f921cf4ba443fb6d806baf1',
                                                                                                      u'branch': [{
                                                                                                                      u'SHA1': u'b868e71f5419311c3f921cf4ba443fb6d806baf1',
                                                                                                                      u'name': u'detached'}]}},
                                                                                    u'origin/IOS-2601': {
                                                                                        u'buildNumber': 15,
                                                                                        u'buildResult': None,
                                                                                        u'marked': {
                                                                                            u'SHA1': u'391f538cf3b3e0d5f651dbd6176128d1d2a587a5',
                                                                                            u'branch': [{
                                                                                                            u'SHA1': u'391f538cf3b3e0d5f651dbd6176128d1d2a587a5',
                                                                                                            u'name': u'origin/IOS-2601'}]},
                                                                                        u'revision': {
                                                                                            u'SHA1': u'391f538cf3b3e0d5f651dbd6176128d1d2a587a5',
                                                                                            u'branch': [{
                                                                                                            u'SHA1': u'391f538cf3b3e0d5f651dbd6176128d1d2a587a5',
                                                                                                            u'name': u'origin/IOS-2601'}]}},
                                                                                    u'origin/IOS-2539': {
                                                                                        u'buildNumber': 16,
                                                                                        u'buildResult': None,
                                                                                        u'marked': {
                                                                                            u'SHA1': u'857397c8620c01b0c090cacf39a75364373a42e8',
                                                                                            u'branch': [{
                                                                                                            u'SHA1': u'857397c8620c01b0c090cacf39a75364373a42e8',
                                                                                                            u'name': u'origin/IOS-2539'}]},
                                                                                        u'revision': {
                                                                                            u'SHA1': u'857397c8620c01b0c090cacf39a75364373a42e8',
                                                                                            u'branch': [{
                                                                                                            u'SHA1': u'857397c8620c01b0c090cacf39a75364373a42e8',
                                                                                                            u'name': u'origin/IOS-2539'}]}}},
                                                                                u'remoteUrls': [
                                                                                    u'https://github.com/Victorious/VictoriousiOS.git'],
                                                                                u'lastBuiltRevision': {
                                                                                    u'SHA1': u'b868e71f5419311c3f921cf4ba443fb6d806baf1',
                                                                                    u'branch': [{
                                                                                                    u'SHA1': u'b868e71f5419311c3f921cf4ba443fb6d806baf1',
                                                                                                    u'name': u'detached'}]}},
                                                                               {u'causes': [{
                                                                                                u'shortDescription': u'GitHub pull request #1628 of commit e89f0d1b08877a775064c3169fe6475c2dbbaac4 automatically merged.'}]}],
     u'why': u'Waiting for next available executor', u'buildable': True,
     u'params': u'\nAPP_NAMES=victorious\nSEND_NOTIFICATIONS=true\nsha1=origin/pr/1628/merge\nghprbActualCommit=e89f0d1b08877a775064c3169fe6475c2dbbaac4\nghprbActualCommitAuthor=Steven F Petteruti\nghprbActualCommitAuthorEmail=steven@stevens-mac-mini.local\nghprbTriggerAuthor=\nghprbTriggerAuthorEmail=\nghprbPullId=1628\nghprbTargetBranch=dev\nghprbSourceBranch=comment-animation\nGIT_BRANCH=comment-animation\nghprbPullAuthorEmail=\nghprbPullDescription=GitHub pull request #1628 of commit e89f0d1b08877a775064c3169fe6475c2dbbaac4 automatically merged.\nghprbPullTitle=added a nice animation when user leaves a comment\nghprbPullLink=https://github.com/Victorious/VictoriousiOS/pull/1628',
     u'buildableStartMilliseconds': 1438992666800, u'id': 1130, u'pending': False, u'blocked': False},
 {u'task': {u'url': u'http://devs-imac.local:8080/job/iOS%20QA%20Build/', u'color': u'blue', u'name': u'iOS QA Build'},
  u'stuck': True, u'url': u'queue/item/1129/', u'inQueueSince': 1438992182105, u'actions': [{u'causes': [
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'},
     {u'shortDescription': u'Started by an SCM change'}, {u'shortDescription': u'Started by an SCM change'}]}, {
                                                                                                u'parameters': [{
                                                                                                                    u'name': u'APP_NAMES',
                                                                                                                    u'value': u'victorious EatYourKimchi iVictorious GlamLifeGuru Pwnisher Copa90Football TheYoungTurks'},
                                                                                                                {
                                                                                                                    u'name': u'SEND_NOTIFICATIONS',
                                                                                                                    u'value': True}]}],
  u'why': u'Waiting for next available executor', u'buildable': True,
  u'params': u'\nAPP_NAMES=victorious EatYourKimchi iVictorious GlamLifeGuru Pwnisher Copa90Football TheYoungTurks\nSEND_NOTIFICATIONS=true',
  u'buildableStartMilliseconds': 1438992190100, u'id': 1129, u'pending': False, u'blocked': False}]
